package org.firstinspires.ftc.teamcode.pedro;

import com.pedropathing.algorithm.Foresight;
import com.pedropathing.algorithm.ForesightConfig;
import com.pedropathing.controllers.Controller;
import com.pedropathing.follower.Follower;
import com.pedropathing.math.Matrix;
import com.pedropathing.math.Vector2D;
import com.pedropathing.revhub.drivetrains.Mecanum;
import com.pedropathing.revhub.drivetrains.MecanumConfig;
import com.pedropathing.revhub.localizers.PinpointConfig;
import com.pedropathing.revhub.localizers.PinpointLocalizer;
import com.qualcomm.hardware.gobilda.GoBildaPinpointDriver;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;
import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;

public class Constants {

    // Dead wheel geometry, measured on our U-shape chassis (verified by spin test 2026-10-03):
    //   parallel pod (measures forward/back): 50 mm RIGHT of robot center
    //   perpendicular pod (measures strafe):  30 mm BEHIND robot center
    // Pinpoint signs (left/forward = positive): X offset -50 mm, Y offset -30 mm
    // Offsets below converted to inches: -50 mm = -1.9685 in, -30 mm = -1.1811 in.

    // Drivetrain — generated by the AutoTune "Mecanum Tuner"
    public static MecanumConfig drivetrainConfig = new MecanumConfig(c -> {
        c.frontLeftName.set("lf");
        c.frontRightName.set("rf");
        c.backLeftName.set("lb");
        c.backRightName.set("rb");
        c.frontLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.frontRightDirection.set(DcMotorSimple.Direction.FORWARD);
        c.backLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.backRightDirection.set(DcMotorSimple.Direction.FORWARD);
    });

    // Localizer — goBILDA Pinpoint with our hand-calibrated values
    public static PinpointConfig localizerConfig = new PinpointConfig(c -> {
        c.name.set("pp");
        c.podType.set(GoBildaPinpointDriver.GoBildaOdometryPods.goBILDA_4_BAR_POD);
        c.xPodOffset.set(-1.9685);
        c.yPodOffset.set(-1.1811);
        c.xPodDirection.set(GoBildaPinpointDriver.EncoderDirection.REVERSED);
        // yPod REVERSED: physical left strafe read as y=-23 in the
        // 2026-10-05 odometry log — the pod counts backwards. Left = +y.
        c.yPodDirection.set(GoBildaPinpointDriver.EncoderDirection.REVERSED);
        c.globalDistanceUnit.set(DistanceUnit.INCH);
        c.offsetUnits.set(DistanceUnit.INCH);
    });

    // Algorithm — Foresight.
    // Measured 2026-10-04 via the step-by-step Foresight Steps tuner
    // (hard floor, hallway). headingKP from the bounce-proof step 0.
    // One manual fix applied: strafeLinear was fitted as -0.0504 — a
    // negative linear brake coefficient can produce an imaginary braking
    // speed — clamped to 0.01.
    public static ForesightConfig foresightConfig = new ForesightConfig(
            c -> {
                Controller primaryTranslationalForward = Controller.proportional(2.544133433929248);
                Controller secondaryTranslationalForward = Controller.proportional(0.9399893233394881);
                Controller primaryTranslationalLateral = Controller.proportional(0.9482677459839527);
                Controller secondaryTranslationalLateral = Controller.proportional(0.35035959396023786);

                c.forwardTranslational.set(Controller.piecewise(secondaryTranslationalForward).put(2.5, primaryTranslationalForward));
                c.strafeTranslational.set(Controller.piecewise(secondaryTranslationalLateral).put(2.5, primaryTranslationalLateral));
                c.coast.set(Controller.proportionalFeedforward(0.014520331493896447));
                c.brake.set(Controller.proportionalFeedforward(0.01234228176981198));

                // Heading gain, tuned empirically 2026-10-05:
                //   9.45  -> saturates beyond 6 deg of error = bang-bang seizure
                //   0.165 -> below static friction, no rotation at all
                //   -1.0  + staticFF 0.1 -> proportional band ~+-57 deg,
                //           feedforward pushes through friction near target.
                // Negative sign: the rotation sign convention is flipped in
                // the localizer->Foresight chain (see frame probe history).
                // Positive sign converges (post yPod-fix). Tracking a heading
                // ramp has steady-state lag ∝ rampRate/gain: 0.5 lagged ~20
                // deg behind the sweep. 0.8 closes most of it.
                c.headingFeedback.set(Controller.proportional(0.8));
                // If it stalls short of the target heading, add static
                // friction feedforward here: c.headingStaticFF takes a
                // Controller, e.g. Controller.proportionalFeedforward(0.1)
                c.headingBrakeCoefficients.set(Vector2D.cartesian(0.09629034133863262, -0.002765392395272116));

                c.linearBrakeCoefficients.set(Matrix.diag(0.1217654664399522, 0.01));
                c.quadraticBrakeCoefficients.set(Matrix.diag(3.961044217824887E-4, 0.004067698781707838));

                c.maxAchievableForwardVelocity.set(80.9295009503824);
                c.maxAchievableStrafeVelocity.set(69.83964272080335);
                c.naturalForwardDeceleration.set(761.4730322127768);
                c.naturalStrafeDeceleration.set(811.3685206465822);
            }
    );

    public static Follower create(HardwareMap h) {
        return new Follower(
                new PinpointLocalizer(h, localizerConfig),
                new Mecanum(h, drivetrainConfig),
                new Foresight(foresightConfig));
    }
}
