package org.firstinspires.ftc.teamcode.pedro;

import com.pedropathing.algorithm.Foresight;
import com.pedropathing.algorithm.ForesightConfig;
import com.pedropathing.controllers.Controller;
import com.pedropathing.follower.Follower;
import com.pedropathing.math.Matrix;
import com.pedropathing.math.Vector2D;
import com.pedropathing.revhub.drivetrains.Mecanum;
import com.pedropathing.revhub.drivetrains.MecanumConfig;
import com.pedropathing.revhub.localizers.PinpointConfig;
import com.pedropathing.revhub.localizers.PinpointLocalizer;
import com.qualcomm.hardware.gobilda.GoBildaPinpointDriver;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;
import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;

public class Constants {

    // Dead wheel geometry, measured on our U-shape chassis (verified by spin test 2026-10-03):
    //   parallel pod (measures forward/back): 50 mm RIGHT of robot center
    //   perpendicular pod (measures strafe):  30 mm BEHIND robot center
    // Pinpoint signs (left/forward = positive): X offset -50 mm, Y offset -30 mm
    // Offsets below converted to inches: -50 mm = -1.9685 in, -30 mm = -1.1811 in.

    // Drivetrain — generated by the AutoTune "Mecanum Tuner"
    public static MecanumConfig drivetrainConfig = new MecanumConfig(c -> {
        c.frontLeftName.set("lf");
        c.frontRightName.set("rf");
        c.backLeftName.set("lb");
        c.backRightName.set("rb");
        c.frontLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.frontRightDirection.set(DcMotorSimple.Direction.FORWARD);
        c.backLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.backRightDirection.set(DcMotorSimple.Direction.FORWARD);
    });

    // Localizer — goBILDA Pinpoint with our hand-calibrated values
    public static PinpointConfig localizerConfig = new PinpointConfig(c -> {
        c.name.set("pp");
        c.podType.set(GoBildaPinpointDriver.GoBildaOdometryPods.goBILDA_4_BAR_POD);
        c.xPodOffset.set(-1.9685);
        c.yPodOffset.set(-1.1811);
        c.xPodDirection.set(GoBildaPinpointDriver.EncoderDirection.REVERSED);
        c.yPodDirection.set(GoBildaPinpointDriver.EncoderDirection.FORWARD);
        c.globalDistanceUnit.set(DistanceUnit.INCH);
        c.offsetUnits.set(DistanceUnit.INCH);
    });

    // Algorithm — Foresight.
    // !!! PLACEHOLDER VALUES !!! The structure and field list come from the
    // Foresight tuner's own code generator, but the numbers are gentle
    // guesses, NOT tuned for this robot. Run the Foresight tuner in
    // AutoTune and paste its generated block over this whole lambda.
    public static ForesightConfig foresightConfig = new ForesightConfig(c -> {
        Controller primaryTranslationalForward = Controller.proportional(0.03);
        Controller secondaryTranslationalForward = Controller.proportional(0.015);
        Controller primaryTranslationalLateral = Controller.proportional(0.02);
        Controller secondaryTranslationalLateral = Controller.proportional(0.01);

        c.forwardTranslational.set(Controller.piecewise(secondaryTranslationalForward).put(2.5, primaryTranslationalForward));
        c.strafeTranslational.set(Controller.piecewise(secondaryTranslationalLateral).put(2.5, primaryTranslationalLateral));

        c.coast.set(Controller.proportionalFeedforward(0.02));
        c.brake.set(Controller.proportionalFeedforward(0.025));

        c.headingFeedback.set(Controller.proportional(0.04));

        c.headingBrakeCoefficients.set(Vector2D.cartesian(0.5, 0.2));

        c.linearBrakeCoefficients.set(Matrix.diag(0.2, 0.15));
        c.quadraticBrakeCoefficients.set(Matrix.diag(0.05, 0.05));

        c.maxAchievableForwardVelocity.set(40.0);
        c.maxAchievableStrafeVelocity.set(25.0);
        c.naturalForwardDeceleration.set(30.0);
        c.naturalStrafeDeceleration.set(20.0);
    });

    public static Follower create(HardwareMap h) {
        return new Follower(
                new PinpointLocalizer(h, localizerConfig),
                new Mecanum(h, drivetrainConfig),
                new Foresight(foresightConfig));
    }
}
